name: zappyplay
description: "desktop video player."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: ^8.2.0

  # Desktop Window Control
  window_manager: ^0.5.1

  # Media
  media_kit: ^1.2.0 
  media_kit_video: ^1.3.0 
  media_kit_libs_video: ^1.0.6

  # File System
  path: ^1.9.1
  file_picker: ^10.3.2
  desktop_drop: ^0.6.1
  path_provider: ^2.1.5
  json_annotation: ^4.9.0

  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/i18n/
