name: zappyplay
description: "desktop video player."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.0.3

  # Desktop Window Control
  window_manager: ^0.5.1

  # Media
  media_kit: ^1.2.0 # Primary package.
  media_kit_video: ^1.3.0 # For video rendering.
  media_kit_libs_video: ^1.0.6 # Native video dependencies.

  # File System
  path: ^1.9.1
  file_picker: ^10.2.3
  path_provider: ^2.1.5
  json_annotation: ^4.9.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
